src/native/api.c
src/native/api.h

This change adds a function which returns text name of the given HTTP method.
Fixes #6

Add a function which returns textual name of HTTP method

---

src/llhttp/http.ts
test/request/transfer-encoding.md

This change fixes the bug that chunked encoding can end without seeing last-chunk.  More specifically, reading just extra `\r\n\r\n` persuades llhttp that chunked encoding finished.
Fixes #20

Fix bug that chunked encoding ends without last-chunk

---

README.md

https://github.com/nodejs/llhttp/pull/16 updated the link URL but omitted updating the image URL.

Fix build status badge image URL

---

README.md

`llhttp_set_type` doesn't exist in the C API.
Signed-off-by: Derek Argueta <dereka@pinterest.com>

docs: remove misleading README docstring

---

package.json

I think other repos which was moved to `nodejs` org also have wrong urls (from other side this is OK because redirect work).

Small package json fixes

---

bin/generate.ts

Solution from issue #35 
btw, why there 2 ways for generate?
- `make generate`
- `npm run build`

Fix shebang in generate script

---

.github/workflows/ci.yaml
.travis.yml
Makefile
README.md
package-lock.json
package.json
test/md-test.ts

Why GitHub Actions? Because support 3 platform at one place.
Are you interesting in running tests on Windows? (will need extra efforts in `llparse-test-fixtures` for fixing `sys/time.h` header)
CI files can be applied to other llhttp repos.
CI status: https://github.com/fanatid/llhttp/actions

ci: change travis to gh actions + Windows support

---

src/llhttp/http.ts
test/fixtures/extra.c
test/request/connection.md
test/request/content-length.md
test/request/finish.md
test/request/invalid.md
test/request/lenient-headers.md
test/request/method.md
test/request/sample.md
test/request/transfer-encoding.md
test/request/uri.md
test/response/connection.md
test/response/content-length.md
test/response/finish.md
test/response/invalid.md
test/response/sample.md
test/response/transfer-encoding.md

In 4cc13c0, the `on_header_field_complete` callback was added.  However,
special header fields take a different path out than general header fields,
so this callback would not be called for them.  This change hooks that path
up to the callback.  In general, any call to `span.headerField.end()` should
be followed by `onHeaderFieldComplete`.
I preëmptively checked to make sure that there was not a similar mistake in
`on_header_value_complete` and there was, specifically for any field except
Content-Length with a completely empty value.  Empty Content-Length is an
error, and the path that checks this was not hooked up.  Now it is too.  In
general, the header value states should never directly transition back to
`header_field_start`, they should poke `onHeaderValueComplete`.
Issue: …

http: fix header completion callbacks for special fields & empty values

---

Makefile

Note that the objects must be built with -fPIC now.  Tested with both clang
and gcc.
Issue: #52

makefile: build & install shared library

---

src/native/api.c
src/native/api.h

This change adds a helper method that resets the state of an existing, already initialized parser, preserving the type, settings, user data, and flags.  This is useful for wrappers that want to reset the internal parser state without having to manually save and restore the configuration state.

api: add llhttp_reset

---

README.md

Sorry if this sounds silly to you, but when I first tried out this project, I thought I have to look back on [http_parser][] in order to find out what callback functions could I use. Not until I saw you mention in [this issue][issue] did I realize that they were already thoroughly documented in [api.h][]. Therefore, I think it would be beneficial if we include this single line in README.md.
Another silly thought: I'm afraid that some developers are not familiar to building a node project. Therefore, it would be nice if there is a _build instruction_ within README.md, since a simple `make` won't work.
[http_parser]: https://github.com/nodejs/http-parser
[issue]: https://github.com/nodejs/llhttp/issues/98
[api.h]: https://github.com/nodejs/llhttp/blob/master/src/native/api.h

readme: add a link to api.h for better guidance

---

test/fuzzers/fuzz_parser.c

This adds a fuzzing set up to llhttp and OSS-Fuzz - much similar to what we did with http-parser: https://github.com/nodejs/http-parser/tree/master/fuzzers
The OSS-Fuzz set up here: https://github.com/google/oss-fuzz/pull/5850
Is this something you would be interested in? it would be great to get the parser fuzzed - the only thing we will need is an email(s) that will receive bug reports, coverage reports and more.

Add fuzzing set up

---

src/native/api.h

For non wasm compiles, there is no API for us to access attributes such as HTTP method and status code, as described in #111.

api: make the wasm methods public

---

README.md

When I build this project the first time, what I got after running `make` was:
```
npx: command not found
```
So I googled around and installed `nodejs` and other stuff. But then `npm` told me it failed to compile, so I spent more time to found that I have to run `npm i` for the unmet dependencies. So I think maybe a short guidance in the README would be great.

readme: add installation instructions

---

Makefile

See also: https://github.com/nodejs/llhttp/pull/125
Fixes:
```
$ npm install
$ make release
$ cmake -S release -B releasebuild
[…]
CMake Error: File /home/ben/src/forks/llhttp/release/libllhttp.pc.in does not exist.
CMake Error at CMakeLists.txt:41 (configure_file):
configure_file Problem configuring file
[…]
```

Also copy libllhttp.pc.in to release directory

---

CMakeLists.txt
Makefile

1. replace previous "VERSION 6.0.5" by "VERSION \_TAG\_" in CMakelists.txt
2. e.g. "TAG=6.0.7 make release" will now use sed to replace \_TAG\_ by 6.0.7 in release/CMakeLists.txt
3.  "make release" will also now include the recent addition libllhttp.pc.in  when updating the release branch.

corrections to Makefile and CMakeLists.txt for correct releases

---

src/llhttp/constants.ts
src/llhttp/http.ts
test/fixtures/extra.c
test/fixtures/index.ts
test/md-test.ts
test/request/invalid.md
test/request/lenient-version.md
test/response/invalid.md
test/response/lenient-version.md

Fixes https://github.com/nodejs/node/issues/43115 on Node 16+.
A backport is needed for llhttp 2.x, used by Node 14.

http: validate HTTP version

---

Makefile

improve Makefile install

---

Makefile
docs/releasing.md
package.json

Hello!
This PR aims to streamline and standardize the release procedure for llhttp by adding a Makefile task and reference document.

feat: Added release guide.

---

src/native/api.c

Hi,
while writing LuaJIT bindings for this library I noticed something peculiar:
* In [this merged PR](https://github.com/nodejs/llhttp/pull/142/files) certain wasm APIs were made public *in the header file only*
* The implementation itself is however [still guarded by the WebAssembly define](https://github.com/nodejs/llhttp/blob/0560647932f277192a120b9aad57da13016bedaa/src/native/api.c#L42-L109)
* As a result, [the define is still present in the latest release](https://github.com/nodejs/llhttp/blob/6d954cbdc7f641f0a63a4427cf4d6be397f74ee8/src/api.c#L42-L109), which I've been using
Accordingly, I'm unable to bind these functions (without hacks). This PR should fix the problem, hopefully without side effects.
Since I'm not sure about the wasm stuff I simply moved the define upwards instead …

Remove a __wasm__  define guard around public APIs

---

src/llhttp/http.ts
test/request/transfer-encoding.md
test/response/transfer-encoding.md

feat: Require semicolon to start chunk parameters.

---

README.md
src/llhttp/constants.ts
src/llhttp/http.ts
src/native/api.c
src/native/api.h
test/fixtures/extra.c
test/md-test.ts
test/request/pausing.md
test/request/transfer-encoding.md
test/response/pausing.md
test/response/transfer-encoding.md

This PR parses chunk extensions as defined in RFC 7230.
It also add the `on_chunk_extension_name`, `on_chunk_extension_value`, `on_chunk_extension_name_complete` and `on_chunk_extension_value_complete` callbacks. 
Fixes #153.

http: added chunked extensions parsing and related callbacks

---

src/llhttp/http.ts
test/fixtures/extra.c
test/md-test.ts
test/request/content-length.md
test/response/content-length.md

fix: Reset Content-length upon reset.

---

Dockerfile
bin/build_wasm.ts
package.json

I've added a `process.env.WASM_PLATFORM` to the build script to select the platform to build Docker image for.
Also, I've updated Docker image to be smaller and to use Node 16 to build.
Fixes #208.

feat: Allow to select WASM platform when using Docker.

---

Makefile
package.json
src/llhttp.gyp
src/llhttp/http.ts
test/request/invalid.md
test/request/lenient-headers.md
test/request/sample.md

This PR forbids empty header separated by CR when no leniency is allowed.
Fixes: https://hackerone.com/reports/2001873

[v6.x] fix: Do not allow empty header separated by CR.

---

Makefile

Make the release target in the Makefile more portable.
See conversation: https://github.com/nodejs/llhttp/commit/7e18596bae8f63692ded9d3250d5d984fe90dcfb#r119290262

Do not assume a particular sed implementation

---

README.md
bench/index.ts
bin/generate.ts
package.json
src/llhttp.ts
src/llhttp/constants.ts
src/llhttp/http.ts
src/llhttp/url.ts
src/native/api.c
src/native/api.h
test/fixtures/extra.c
test/fixtures/index.ts
test/md-test.ts
test/request/connection.md
test/request/content-length.md
test/request/invalid.md
test/request/sample.md
test/request/transfer-encoding.md
test/request/uri.md
test/response/connection.md
test/response/invalid.md
test/response/sample.md
test/url.md

This PR drops completely the strict mode in favor of three new leniency flags.

feat: Drop strict mode in favor of leniency flags.

---

src/llhttp/http.ts
test/fixtures/extra.c
test/fixtures/index.ts
test/request/content-length.md
test/response/invalid.md

fix: Support all LF messages.

---

README.md
src/llhttp/constants.ts
src/llhttp/http.ts
src/native/api.c
test/fixtures/extra.c
test/fixtures/index.ts
test/request/connection.md
test/request/content-length.md
test/request/invalid.md
test/request/lenient-headers.md
test/request/lenient-version.md
test/request/sample.md
test/request/transfer-encoding.md
test/response/connection.md
test/response/invalid.md
test/response/lenient-version.md
test/response/sample.md

New lenient flag to make CR completely optional.

---

src/llhttp/http.ts
test/request/transfer-encoding.md

Fix: Chunk extensions' parameters parsing when more then one name-value pair provided
Consider multiple name-value pairs in the extensions line (chunk extension).

Fix: Chunk ext parameters parsing when more then one name-value

---

src/native/api.c

Newer lenient flags `LENIENT_OPTIONAL_CR_BEFORE_LF` `LENIENT_SPACES_AFTER_CHUNK_SIZE` are lost during `llhttp_reset`

lenient_flags is truncated on reset

---

src/llhttp/constants.ts
src/llhttp/http.ts
test/request/transfer-encoding.md

According to [rfc9112](https://datatracker.ietf.org/doc/html/rfc9112) quoted string is defined by [rfc9110](https://datatracker.ietf.org/doc/html/rfc9110)
```
quoted-string = <quoted-string, see [HTTP], Section 5.6.4>
```
The definition of quoted-string also uses a notion of quoted-pair:
```
quoted-pair    = "\" ( HTAB / SP / VCHAR / obs-text )
```
This change makes the parsing of quoted-string aware of quoted-pairs and makes it possile to handle valid quoted strings.
References:
* https://datatracker.ietf.org/doc/html/rfc9112#name-syntax-notation
* https://datatracker.ietf.org/doc/html/rfc9112#name-chunk-extensions
* https://datatracker.ietf.org/doc/html/rfc9110#section-5.6.4

Fix chunk extensions quoted-string value parsing

---

src/native/http.c
test/response/connection.md

fix: Restart the parser on HTTP 100.

---

src/native/http.c
test/response/connection.md
test/response/transfer-encoding.md

This test fails on 9.1.3 but passes on 8.1.1
related issues https://github.com/aio-libs/aiohttp/pull/7697 https://github.com/home-assistant/core/issues/101893 https://github.com/home-assistant/core/pull/101913

Fix zero length chunked response regression

---

src/llhttp/http.ts
test/request/invalid.md

Verify that HTTP header fields are not empty.

---

src/native/http.c
test/response/connection.md
test/response/transfer-encoding.md

Reverts nodejs/llhttp#256
It looks like we will need to remove the header in aiohttp instead cc @Dreamsorcerer 
https://github.com/nodejs/llhttp/pull/256#issuecomment-1782909852

Revert "Fix zero length chunked response regression"

---

src/llhttp/http.ts
src/native/api.c
src/native/api.h
test/fixtures/extra.c
test/request/transfer-encoding.md
test/response/transfer-encoding.md

This PR adds a new callback which is invoked every time a chunk extensions character is sent.

feat: Added on_chunk_parameters callback.

---

src/llhttp/constants.ts
test/request/method.md

The HTTP QUERY method is still in draft https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html,
being low impact I think we could implement it.
As pointed by @ShogunPanda in the feature request https://github.com/nodejs/node/issues/51562, it's the first step

feat: support http method query

---

.github/workflows/codeql.yml

without python code, we will just get errors in codeql runs.

remove python from codeql

---

.github/workflows/aiohttp.yml
.github/workflows/ci.yaml
README.md

Currently, the README and workflows are using `npm install`, which does not preserve the lock file.  This change switches to using clean installs with `npm ci`.
Note the `Dockerfile` does already correctly use a clean install.

Use clean installs from MPN

---

src/llhttp/http.ts
test/request/connection.md
test/request/invalid.md
test/request/sample.md
test/request/transfer-encoding.md
test/response/transfer-encoding.md

Ref: [CVE-2024-27982](https://nodejs.org/en/blog/vulnerability/april-2024-security-releases/#http-request-smuggling-via-content-length-obfuscation---cve-2024-27982---medium)

fix: Do not allow OBS fold in headers by default.

---

.github/dependabot.yml

This way, we can disable all dependabot PRs from private forks – I'm fed up with the flow of useless notifications coming from our nodejs-private org.
Refs: https://github.com/nodejs/node/pull/56427

chore: use a configurable value for number of open Dependabot PRs

---

.github/workflows/aiohttp.yml

Seems like the `-X dev` is suddenly not enabling dev mode correctly for some bizarre reason. Trying an alternative way to enable it.

Fix aiohttp dev mode tests

---

CMakeLists.txt
Makefile

chore: Fixed license path and CMake minimum version.

---

.github/dependabot.yml

It looks like the YAML parser needs some nudge to correctly parse the file for some reason.

chore: fix `dependabot.yml`

---

README.md

chore: Updated README.

---

CMakeLists.txt

llhttp_shared is already set in line 87 when BUILD_SHARED_LIBS is true.
Fix #671.

Remove duplicate target
